export type EvaluationJob = { name: string; title: string; text: string };

export const evaluationJobs: EvaluationJob[] = [
  { name: "product-engineer", title: "Product Engineer", text: "Product Engineer at Northstar Learning. Turn ambiguous customer needs into shipped React and TypeScript product features. Define interaction behavior, model application data, integrate external APIs, investigate production failures, and collaborate with design. Direct education experience is helpful but not required." },
  { name: "ai-application-engineer", title: "AI Application Engineer", text: "AI Application Engineer at Signal Tools. Build production language-model features with context retrieval, tool use, structured outputs, validation, application state, and secure backend APIs. Own TypeScript product integration and evaluate model latency, quality, and cost. Foundation-model training is not required." },
  { name: "forward-deployed-technical", title: "Forward-Deployed Technical Lead", text: "Work directly with enterprise customers to discover operational problems, prototype useful AI workflows, connect customer systems and data, turn successful prototypes into dependable implementations, troubleshoot deployments, and communicate tradeoffs across technical and business teams. Frequent customer travel is required." },
  { name: "ai-solutions", title: "AI Implementation and Solutions Consultant", text: "Help customers identify valuable AI use cases, design implementation plans, integrate APIs and business systems, configure context and validation, build proofs of concept, and guide adoption. Success depends on technical judgment, customer communication, and moving from ambiguity to working workflows." },
  { name: "technical-product-manager", title: "Technical Product Manager", text: "Define a new workflow automation product, investigate customer needs, shape product behavior, coordinate engineering and design, reason about APIs and data constraints, evaluate prototypes, and carry decisions through launch. Five years with this exact title is preferred, not mandatory." },
  { name: "ai-transformation", title: "AI Transformation Lead", text: "Identify where AI can improve internal work, redesign processes around people and agents, create prototypes, establish review and evaluation practices, guide teams through adoption, and connect business needs to implementation constraints. Substantial organizational change leadership is important." },
  { name: "product-operations", title: "Product Operations Lead", text: "Improve how product information moves between customers, support, product, and engineering. Diagnose broken workflows, design operational systems, integrate tools, define useful reporting, and coordinate implementation. Experience managing a team of ten is preferred." },
  { name: "automation-systems", title: "Internal Automation Systems Builder", text: "Find repetitive operational work, map the underlying process, build internal tools and integrations, connect third-party systems, model state and permissions, and maintain automations in production. The stack includes TypeScript and low-code platforms, but equivalent experience is accepted." },
  { name: "innovation-prototyping", title: "Innovation Prototyping Lead", text: "Turn uncertain opportunities into testable prototypes, combine software and AI services, design interaction concepts, learn unfamiliar technologies quickly, evaluate results with users, and decide what should be productionized. This is an individual-contributor role." },
  { name: "technical-chief-of-staff", title: "Technical Chief of Staff", text: "Help the founder turn ambiguous priorities into operating systems, investigate technical and product questions, prototype internal workflows, coordinate cross-functional execution, prepare decision material, and follow important initiatives through implementation. Executive communication is central." },
  { name: "research-builder", title: "Research and Analytical Systems Builder", text: "Investigate unfamiliar markets, structure evidence, build small analytical tools, connect data sources, use AI carefully for synthesis, validate outputs, and turn findings into decision-ready workflows. Formal academic research credentials are helpful but not required." },
  { name: "deep-infrastructure", title: "Senior Site Reliability Engineer", text: "Own large-scale Kubernetes and AWS infrastructure, author Terraform modules, operate Kafka, lead on-call and incident response, define SLOs and capacity plans, debug Linux networking, and harden production infrastructure. Seven years of direct SRE ownership is required." },
  { name: "people-management", title: "Vice President of Engineering", text: "Manage an organization of forty engineers through six managers, own hiring and performance systems, lead reorganizations, set compensation and promotion practices, manage a multimillion-dollar budget, and coach senior engineering leaders. Extensive executive people-management history is required." },
  { name: "credentialed-profession", title: "Certified Public Accountant", text: "Sign audited financial statements, provide regulated assurance services, apply GAAP and audit standards, and maintain an active CPA license in California. An active CPA license is legally required." },
  { name: "emerging-role", title: "Agent Workflow Architect", text: "Discover high-value organizational work that can be performed by people and AI agents together. Translate ambiguous goals into agent-ready tasks, design persistent context and review loops, prototype integrations, define evaluation and human-control boundaries, and operationalize successful workflows. The title is new; demonstrated ability matters more than conventional background." },
];
